### ISSUE TITLE
@Li Bin

### ISSUE THREAD

**Issue by Afeihan** [lbbc1117/DeepLearningUFLDL#1]
I ran into a problem when running the cnn-exercise program：

Error in ==> cnnExercise at 68
load stlTrainSubset.mat % loads numTrainImages, trainImages, trainLabels
 
So,file is not provided  the stlTrainSubset.mat .Can you give me the one.I would appreciate it

**Comment by lbbc1117** [comment]
This file was provided by the course. You can down load it from [http://ufldl.stanford.edu/wiki/resources/stlSubset.zip](http://ufldl.stanford.edu/wiki/resources/stlSubset.zip)
